version: "2"

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run start:dev



  database:
    image: postgres:12
    ports:
      - ${PGPORT}:${PGPORT}
    env_file: ".env"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
