version: "3.8"

services:
  server:
    container_name: server
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file: ".env"
    networks:
      - appnet
    depends_on:
      - dev_database
    ports:
      - "3001:3001"
    command: npm run start:dev



  dev_database:
    container_name: dev_database
    image: postgres:12
    networks:
      - db_dev
    ports:
      - "5432:5432"
    volumes:
      - db_val:/var/lib/postgresql/data
    env_file: ".env"

  test_database:
      container_name: test_database
      image: postgres:12
      networks:
        - db_test
      ports:
        - "5435:5432"
      volumes:
        - db_test_val:/var/lib/postgresql/data
      env_file: ".env.test"



networks:
  appnet:
  db_dev:
  db_test:


volumes:
  db_val:
    driver: local
  db_test_val:
    driver: local
