-- AlterTable
ALTER TABLE "ModToProd" ALTER COLUMN "sum" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "ModToProdToOrder" ALTER COLUMN "totalProductPrice" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Modifier" ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Order" ALTER COLUMN "totalPrice" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "ProductOrder" ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Transaction" ADD COLUMN     "refund" TEXT,
ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;
